fix syntax error

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -33,8 +33,8 @@ script:
 after_success:
   - |
     if [[ "$COVERAGE" == "true" ]]; then
-      coveralls; || echo "failed"
-      codecov; || echo "failed"
+      coveralls || echo "failed"
+      codecov || echo "failed"
     fi
 after_script:
   - travis-cleanup
