configure codecov

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -31,7 +31,11 @@ script:
       python setup.py test --addopts --cov=src/
     fi
 after_success:
-  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
+  - |
+    if [[ "$COVERAGE" == "true" ]]; then
+      coveralls; || echo "failed"
+      codecov; || echo "failed"
+    fi
 after_script:
   - travis-cleanup
 cache:
